### ISSUE TITLE
IMU orientation transform

### ISSUE THREAD

**Issue by pdrews** [AutoRally/autorally#14]
Verify/fix the transform from the IMU internal navigation frame (published on /imu/filter) to the state estimator navigation frame.  This issue may be caused by a poorly calibrated magnetometer inside the IMU, or a problem with the transform.  More investigation is needed to determine.

**Comment by myxyzy** [comment]
Hello, 
I was looking for car sensors and come across with this IMU  issue. Is this still open issue?

**Comment by JasonGibson274** [comment]
I'll let @pdrews answer to be fully sure but I do not think so. Our localization stack works as expected so I think it was a transform issue.

**Comment by pdrews** [comment]
I'm not sure what the original intent of this issue was, but it currently works fine so we can close it.
