### ISSUE TITLE
Missing chassisCommandPriorities config

### ISSUE THREAD

**Issue by sfowlr** [AutoRally/autorally#31]
Autorally Gazebo launch file autoRallyTrackGazeboSim.launch calls for chassisCommandPriorities.yaml on line 89:
`<rosparam param="chassisCommandProirities" command="load" file="$(env AR_CONFIG_PATH)/chassisCommandPriorities.yaml" />`

However the file doesn't exist. The following error appears in the terminal:
`error loading <rosparam> tag: 
	file does not exist [/home/zzz/catkin_ws/src/autorally/autorally_util/config/chassisCommandPriorities.yaml]
XML is <rosparam command="load" file="$(env AR_CONFIG_PATH)/chassisCommandPriorities.yaml" param="chassisCommandProirities"/>
The traceback for the exception was written to the log file`

**Comment by bgoldfai** [comment]
This is an issue that we fixed, and then reintroduced by accident. 

As a temporary fix you can change `chassisCommandPriorities.yaml` to `servoCommandPriorities.yaml1

I will push an updated version (0.2.2) to GitHub in the next hour after I test it.

**Comment by sfowlr** [comment]
I read through the previous issue where it was mentioned and suspected that may be the cause. Thanks for the quick response.
