### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [AutoRally/autorally#4]
[An extra null pointer check is not needed](http://dietmar-kuehl.de/mirror/c++-faq/freestore-mgmt.html#faq-16.8 "Do I need to check for NULL before delete p?") in [the functions "QNode::imageCallback1" and "QNode::imageCallback2"](https://github.com/AutoRally/autorally/blob/4508587abaf8dc7956dc6356773b84cc0f697754/autorally_core/src/ocs/qnode.cpp#L248 "Update candidates").

**Comment by barulicm** [comment]
Thanks for pointing this out. I've removed those checks in our development branch. This issue will automatically close with our next release.

**Comment by elfring** [comment]
Thanks for [your small source code improvement](https://github.com/AutoRally/autorally/commit/577ee695c96093effa2348094862a1d8d6e98313 "Deletion of two unnecessary checks").
