### ISSUE TITLE
A script to generate track_data.txt file

### ISSUE THREAD

**Issue by alexbuyval** [AutoRally/autorally#55]
I wonder there is any script to generate [track_data.txt](https://github.com/AutoRally/autorally/blob/kinetic-devel/autorally_control/src/path_integral/params/maps/gazebo/track_data.txt) file for new track?

**Comment by gradyrw** [comment]
Right now there is not a general purpose script to help with creating a costmap for a new track. If you create a costmap yourself, you can save it in the track_data format and use it with the MPPI controller. The track_data.txt format is the following:

minimum x-value (in meters)
maximum x-value (meters)
minimum y-value (meters)
maximum y-value (meters)
grid resolution (i.e. how many grid points make up 1 meter)
grid values in row-major order

**Comment by alexbuyval** [comment]
Thank you for quick response!
