### ISSUE TITLE
chassisState not published without control input

### ISSUE THREAD

**Issue by jisacks** [AutoRally/autorally#68]
When I do not use a joystick and instead attempt to manually set runstopMotionEnabled by publishing to runstop topic with the rqt_publisher or a Python script, I found that chassisState was not being published by the simulator. Instead I get the following warning:

```
WARNING: no messages received and simulated time is active.
Is /clock being published?
```

However, when I enable runstopMotionEnabled from the AutoRally OCS and set the control from the Control tab, I can then do a rostopic echo /chassisState successfully. There are no issues when I use the joystick. It seems that the simulator does not publish chassisState unless it receives control decisions.

**Comment by rdesc** [comment]
Even if I try sending control commands from the control tab in the OCS, I am still not getting anything published on the `/chassisState` topic. Any ideas?

**Comment by rdesc** [comment]
Never mind figured it out! Had to set a delay for launching the controller spawner, since gazebo is slow to come up on my machine. Changes are seen here https://github.com/rdesc/autorally/commit/4c93ece9ab95a59039fad2d0d86ceee682a4ff29

**Comment by JasonGibson274** [comment]
This sounds like gazebo not recognizing the controller interface due to namespacing, it should have been address at this point. Please reopen if the issue is persisting.
