### ISSUE TITLE
MPPI controller information

### ISSUE THREAD

**Issue by yashim** [AutoRally/autorally#7]
Hi!
Do you plan to share the MPPI controller code (mppi_controller)? Where can I find the information/theory about it?

**Comment by bgoldfai** [comment]
We plan to release the MPPI controller as a standalone repository so people can use the controller with whatever system they choose (including the AutoRally platform).

The theory behind the controller is detailed in the publication "Aggressive Driving with Model Predictive Path Integral Control" presented two weeks ago at ICRA 2016. The paper should be available in the next few weeks.

**Comment by yashim** [comment]
Thank you for your answer!
Could you please give an estimate how much time will it take to release MPPI controller?

**Comment by bgoldfai** [comment]
Hopefully by the end of the summer, but right now we're not sure.

**Comment by bgoldfai** [comment]
The MPPI code is now publicly available in the devel branch, and will be included in the next release.
