### ISSUE TITLE
ROS2 GAZEBO99 - Robot keeps jerking and moving

### ISSUE THREAD

**Issue by tobi007** [AutoRally/autorally#85]
I'm from Nigeria, so I'm trying to set up a simulation for a local autonomous rc car group
I coming up next year.

I'm trying to run autorally uising ros2 and gazebo 9, I was able to build descrption and gazebo package. But when I launch the robot into rviz2 and gazebo, the robots krrps jerking and moving slowly on its own without any commands been sent to joint states topic. Also Whem I send command to joint states topic only the robot in rviz2 receives it but in gazebo it's just jerking and moving.

Any help please

[Screencast from 12-28-2019 11:02:06 AM.zip](https://github.com/AutoRally/autorally/files/4006937/Screencast.from.12-28-2019.11.02.06.AM.zip)

**Comment by tobi007** [comment]
I also tried using the libgazebo_ros_ackermann_drive for ros2 to and publish to the topic, but it still not responding to the command, just jerking and moving.

**Comment by keuntaeklee** [comment]
AutoRally does not support ROS2 yet.

However, please make sure that you installed all the dependencies:
cd ~/catkin_ws
rosdep install --from-path src --ignore-src -y

**Comment by JasonGibson274** [comment]
I am going to close this for now since we do not support ROS 2. If you are having gazebo issues on ROS 1 reopen this issue and put the output with verbose (in the track launch file) enabled.
