### ISSUE TITLE
Generating costmap

### ISSUE THREAD

**Issue by imgeorgiev** [AutoRally/autorally#86]
Not an issue, just a question.

How do you generate costmaps? I have noticed that there are 2 scripts in `autorally/autorally_control/src/path_integral/scripts/ ` but those are just for file type conversion rather than generating the costmaps.

I have made some Python scripts that generate costmaps based off track boundaries. They seem to work but for some reason also decrease the operational speed of the MPPI algorithm with bigger tracks. For example, for a track of size 132664 m^2 with 20 ppm (pixels per meter), the MPPI operational speed drops to ~2.5 Hz. But if the ppm=1 for the same track, MPPI works at whatever the designated frequency is. Have you experienced similar issues?

**Comment by JasonGibson274** [comment]
You are likely using too much memory on your GPU. A costmap gets converted into a CUDA texture before it gets used, so likely the performance hit is you are taking too much memory (that is a huge costmap compared to what we normally use). You will have to decrease resolution and your issue should go away.

When we generate costmaps it is done from a GPS track survey using a custom script which I can provide if you are interested. At the end of the day it is just a npy file of a given format.
